name: Check versions
on:
  issues:
    types: [opened]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: react-navigation/check-versions-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          packages: |
            react-native-gesture-handler-tabview
            react-native-gesture-handler
            react-native-reanimated
